name: AWS EC2 Terraform + Ansible + Docker Automation

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.4.0"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

  ansible:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install ansible -y

      - name: Install Docker on EC2
        run: |
          ansible-playbook -i <EC2-IP>, -u ec2-user --private-key ~/terraform/key_value.pem install_docker.yml

      - name: Deploy Hello World Docker App
        run: |
          ssh -i ~/terraform/key_value.pem ec2-user@<EC2-IP> "docker build -t hello-world ."
          ssh -i ~/terraform/key_value.pem ec2-user@<EC2-IP> "docker run hello-world"
